apiVersion: apps/v1
kind: Deployment
metadata:
  name: webserver
  labels:
    app: dhyanio-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: dhyanio-app
  template:
    metadata:
      labels:
        app: dhyanio-app
    spec:
      containers:
      - name: php-apache
        image: dhyanio/tomcat-maven-nginx:v1
        ports:
        - containerPort: 80